#!/bin/bash
PROVIDER=$(curl -s -H "X-Vault-Token: $(cat /root/.vault-token)" http://localhost:8200/v1/totp/keys/mrrobot | jq .data)
if [ "$PROVIDER" == "null" ]; then
  fail-message "The TOTP provider was not correctly configured under mrrobot"
  exit 1
fi

ISSUER=$(echo "$PROVIDER" | jq -r .issuer)
if [ "$ISSUER" != "Vault" ]; then
  fail-message "Vault is not the issuer"
  exit 1
fi

ACCOUNT=$(echo "$PROVIDER" | jq -r .account_name)
if [ "$ACCOUNT" != "mrrobot@instruqt.com" ]; then
  fail-message "The account_name is not set to mrrobot"
  exit 1
fi

exit 0
