#!/bin/bash
vault secrets enable database

vault write database/config/postgres \
    plugin_name=postgresql-database-plugin \
    allowed_roles="postgres" \
    connection_url="postgresql://{{username}}:{{password}}@postgres:5432/?sslmode=disable" \
    username="postgres" \
    password="notsecure"

exit 0
