template: containers
configuration:
  Containers:
  - Image: gcr.io/instruqt/vault:arcade
    Name: vault
    Ports:
      - 8200
    Privileged: false
    Environment:
      VAULT_ADDR: "http://localhost:8200"
      VAULT_LOG: "debug"
    Resources:
      Memory: 128
    Shell: /bin/bash
  - Image: mysql:8.0.11
    Name: mysql
    Privileged: false
    Ports:
      - 3306
    Environment:
      MYSQL_USER: vault
      MYSQ_PASSWORD: notsecure
    Resources:
      Memory: 128