version: "2"
containers:
- name: vault
  image: gcr.io/instruqt/vault:arcade
  shell: /bin/bash
  ports:
  - 8200
  environment:
    VAULT_ADDR: http://localhost:8200
    VAULT_LOG: debug
  memory: 128
- name: postgres
  image: postgres:10.4-alpine
  ports:
  - 5432
  environment:
    POSTGRES_PASSWORD: notsecure
  memory: 128
