#!/bin/bash
ERRORS=$(curl -s http://localhost:8200/v1/sys/seal-status | jq -r '.errors')
if [ "$ERRORS" != "null" ]; then
  fail-message "Vault is not yet initialized"
  exit 1
fi

SEALED=$(curl -s http://localhost:8200/v1/sys/seal-status | jq -r .sealed)
if [ "$SEALED" == "true" ]; then
  fail-message "Vault is not unsealed"
  exit 1
fi

# Get the unseal key in case we need it later.
VAULT_UNSEAL=$(cat /root/.bash_history | grep -E "^vault operator unseal" | awk '{print $4}')
echo "$VAULT_UNSEAL" > /vault/unseal

# Get the root token in case we need it later.
VAULT_TOKEN=$(cat /root/.bash_history | grep -E "^vault login" | awk '{print $3}')
if [ -z "$VAULT_TOKEN" ]; then
  fail-message "No login with the root token found"
  exit 1
fi


exit 0