#!/bin/bash
CREDENTIALS=$(curl -s -H "X-Vault-Token: $(cat /root/.vault-token)" http://localhost:8200/v1/database/creds/postgres | jq .data)
if [ "$CREDENTIALS" == "null" ]; then
  fail-message "Could not request credentials from the creds/postgres endpoint"
  exit 1
fi

exit 0
