#!/bin/bash

# Check if the user made a read request for the secret/highscore path.
REQUEST=$(cat /vault/audit.log  | jq '. | select(.type == "request" and .request.operation == "read" and .request.path == "secret/highscore")')
if [ -z "$REQUEST" ]; then
  fail-message "No read request found for secret/highscore"
  exit 1
fi

exit 0